import Head from "next/head";
import Navigation from "@/components/Navigation";
import style from "@/styles/Blogs.module.css";
import { useRef, useState } from "react";

export default function Posts({ blogs, users }) {
  const [drawer, setDrawer] = useState(false);
  const [comments, setComments] = useState([]);

  const handleOpenDrawer = async (blogId) => {
    const res = await fetch(
      `https://gorest.co.in//public/v2/posts/${blogId}/comments`
    );
    const data = await res.json();
    setComments(data);
    console.log(data);
    setDrawer(true);
  };
  const handleCloseDrawer = () => setDrawer(false);
  return (
    <>
      <Head>
        <title>Blogs | Synapsis Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigation />
        <div className={style.blogs}>
          {blogs.map((blog) => {
            const user = users.find((user) => user.id === blog.user_id);
            return (
              <div className={style.blog_item} key={blog.id}>
                <h1 className={style.blog_title}>{blog.title}</h1>
                <p className={style.blog_elipsis_body}>{blog.body}</p>
                <div className={style.blog_detail}>
                  <p className={style.blog_name}>
                    {user ? user.name : "Anonim"}
                  </p>
                  <span
                    onClick={() => handleOpenDrawer(blog.id)}
                    className={style.blog_detail_button}
                  >
                    Detail
                  </span>
                </div>
              </div>
            );
          })}
        </div>
      </main>
      <div className={`${style.drawer} ${drawer ? style.drawer_open : ""}`}>
        <div onClick={handleCloseDrawer}>Close</div>
        <div className={style.blog_drawer}>
          <p className={style.blog_creator}>Camilla</p>
          <h1 className={style.blog_title_drawer}>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Maxime vel sit consequatur cumque praesentium error</h1>
          <p className={style.blog_body}>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eveniet, repellendus praesentium et delectus tenetur doloremque reiciendis est aspernatur nihil quo dolore qui dolorem eligendi! Maxime sint laboriosam voluptates consequuntur natus.</p>
        </div>
        <div className={style.comments_drawer}>
          <p className={style.comment_count}>{comments.length} comment</p>
          {comments.length === 0 ? (
            ""
          ) : (
            comments.map((comment) => (
              <div key={comment.id} className={style.comment_item}>
                <h2 className={style.comment_name}>{comment.name}</h2>
                <p className={style.comment_body}>{comment.body}</p>
              </div>
            ))
          )}
        </div>
      </div>
    </>
  );
}

export const getServerSideProps = async () => {
  const res = await fetch(`https://gorest.co.in/public/v2/posts`);
  const data = await res.json();

  const res_users = await Promise.all(
    data.map(async (blog) => {
      const res = await fetch(
        `https://gorest.co.in/public/v2/users/${blog.user_id}`
      );
      const data = await res.json();
      return data;
    })
  );

  return {
    props: {
      blogs: data,
      users: res_users,
    },
  };
};
